version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: prismaProj-backend
    networks:
      - prismaProj-backend-network
  test-db:
    image: postgres:13
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: prismaProj-backend
    networks:
      - prismaProj-backend-network
volumes:
  my-db:
  
networks:
  prismaProj-backend-network: